"""Hi again

Revision ID: ac3db1401758
Revises: 9725f1e5b6d4
Create Date: 2023-07-17 17:08:39.507432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3db1401758'
down_revision = '9725f1e5b6d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
